### ISSUE TITLE
Overestimated minimal number of minimizers

### ISSUE THREAD

**Issue by pirovc** [seqan/raptor#113]
Hi @eseiler 

I was wondering if the minimal number of minimizers is being overestimated here: https://github.com/seqan/raptor/blob/64ffff24691bdc03ee5e42f39dfc32f9b9d54571/src/search/precompute_threshold.cpp#L71

I think the floor should be used instead of ceil, for example:

```
l=14, w=6, k=3
--------------
wwwwww
   kkk
    wwwwww
       kkk
        wwwwww
           kkk
(14-3+1)/(6-3+1) = 3

l=15, w=6, k=3
---------------
wwwwww
   kkk
    wwwwww
       kkk
        wwwwww
           kkk
         wwwwww
           kkk
(15-3+1)/(6-3+1) = 3.25

l=17, w=6, k=3
-----------------
wwwwww
   kkk
    wwwwww
       kkk
        wwwwww
           kkk
           wwwwww
           kkk
(17-3+1)/(6-3+1) = 3.75
```

I tested with the example data and raptor v2.0.0 and the change increased the number of sequences with a bin assigned when using --error 1 (but no changes with --error 2). Let me know if you agree or if I'm missing something. If yes, I can open a PR.

**Comment by eseiler** [comment]
Thanks for detecting!

Yes, we shouldn't `std::ceil` there and the changed results are from using the proper lower bound for the threshold.
