### ISSUE TITLE
Providing a list of input files

### ISSUE THREAD

**Issue by sam217pa** [seqan/raptor#15]
Hi, 

Thanks for developing Raptor!

I am trying to use it on a list of contigs, for which I've precomputed a list of minimisers as indicated in your nice tutorial.

However I'm hitting the bash command line argument length when providing the list of minimisers this way.
I think providing a list of minimisers (tsv file, one minimiser per line) would prevent this from triggering.

I've been looking at the code in `src/raptor.cpp`, and it seems that the input validation is done by the `bin_validation` class.
I'm guessing it shouldn't be too difficult to make it iterate over a list of file names, but I can't figure it out as I can barely read C++. (And Seqan3-level C++20 templated metaprogramming is pure wizardry to me !) 

thanks again,

**Comment by eseiler** [comment]
Hey @sam217pa,

thanks for using raptor :)
I'll have a look at it this afternoon, it shouldn't be too hard to implement.

**Comment by eseiler** [comment]
I merged #16; I will tag a new release and update the packages. If you did compile it yourself, you can use the current master.

**Comment by sam217pa** [comment]
Well thank you very much, that was quick and responsive indeed!
I'll give it a try and let you know how it goes.

Thanks again,
