### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by mr-c** [seqan/raptor#169]
I'd be happy to package raptor for Debian, especially once #167 and #168 are merged.

Can we have a new release with a tag?

**Comment by eseiler** [comment]
I'll have to check whether I introduced breaking changes (especially the index format).
If not, I'm happy to do a (minor) release soon.
Otherwise, I there would be some breakages that I would like to add before doing a major release.

**Comment by mr-c** [comment]
@eseiler Thanks! Also, a complete source archive, like done for seqan3, is necessary

**Comment by mr-c** [comment]
To my great surprise, raptor has been quickly accepted into Debian, congratulations!

https://tracker.debian.org/news/1379871/accepted-seqan-raptor-2000gitfecfbcads-1-source-amd64-all-into-unstable/

Shall I update the commit I'm packaging?

**Comment by eseiler** [comment]
> To my great surprise, raptor has been quickly accepted into Debian, congratulations!
> 
> https://tracker.debian.org/news/1379871/accepted-seqan-raptor-2000gitfecfbcads-1-source-amd64-all-into-unstable/
> 
> Shall I update the commit I'm packaging?

🎉 

You could update the commit, but it doesn't contain any bugfixes or features; it's only infrastructure (and the way the tests are configured and called were changed)
