### ISSUE TITLE
doxygen refers to fastq_to_fasta and not raptor

### ISSUE THREAD

**Issue by mr-c** [seqan/raptor#170]
https://github.com/seqan/raptor/blob/main/doc/doxygen_cfg

:-)

**Comment by eseiler** [comment]
Documentation isn't set up for Raptor yet, so this is kinda expected :D

**Comment by mr-c** [comment]
Ah, okay. I'll remove the `make docs` from the Debian package

**Comment by eseiler** [comment]
I updated the doc config in https://github.com/seqan/raptor/pull/173

To build:
```
mkdir build
cd build
cmake ../test/documentation
make doc
open html/index.html
```

Also deployed via vercel: https://seqan-raptor.vercel.app/
