### ISSUE TITLE
Some extra information about the subcommands

### ISSUE THREAD

**Issue by SGSSGene** [seqan/raptor#171]
For the help/man pages it would be awesome if the subcommands also have description text, similar to the top parser.

https://github.com/seqan/raptor/blob/fecfbca54347addb06e5b5363793e6e87888d14d/src/raptor.cpp#L23-L31

Currently there is no description of what `build`, `search` or `upgrade` do.

**Comment by eseiler** [comment]
Do you have some suggestions what could be set as description? The top-level one is more or less an abstract. `build` does build. `search` does search. `upgrade` upgrades the index to be compatible with a new version.

**Comment by mr-c** [comment]
@eseiler Ideally it should be one or two sentences that describes what the sub-command does, for an audience who is browsing many tools (or exploring a big workflow that uses raptor) but hasn't heard of raptor before.

For example (based upon my limited knowledge of raptor)

build → Constructs a raptor format index of large collections of nucleotide sequences
search → Searches a raptor format index of nucleotide sequences using one or more sequences queries
upgrade → Upgrades a raptor index from format v1.1.0 to v2.0.0

**Comment by mr-c** [comment]
Thanks!
