### ISSUE TITLE
[BUG] The default parameter size throws an error, if not set.

### ISSUE THREAD

**Issue by Irallia** [seqan/raptor#195]
## Platform

  - Raptor version: 2.0.1
  - Operating system: macOS Catalina
  - Source: Compiled from source
  - Compiler: GCC 12.2.0

### How to repeat the problem

Run
`raptor build --output raptor.index all_bin_paths.txt`, e.g. with the example_data.

### Expected behaviour

As the size has a default value, this should work.

### Actual behaviour

`[Error] Option --size is required but not set.`

**Comment by eseiler** [comment]
I'll have to check how to achieve the correct behavior with Sharg.
If there is `--hibf`, `--size` is not allowed. Otherwise, it is required.

I can only check that after parsing the arguments, so Sharg displays a default, although it is either forbidden or required.

**Comment by Irallia** [comment]
When solving this issue, please check the first Assignment in the index tutorial, whether it needs to be adjusted.

**Comment by eseiler** [comment]
`--size` was removed in favor of `--fpr`
