### ISSUE TITLE
No --hibf with actual hibf index and empty query file segfaults

### ISSUE THREAD

**Issue by feldroop** [seqan/raptor#207]
## Platform

  - Raptor version: 2.0.1
  - Operating system: Linux 4.19.128-microsoft-standard SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
  - Source: from source
  - Compiler: gcc 10

## Description

I originally observed that raptor segfaults when an empty fastq file is given. In the process of finding what causes the problem, I also found out that supplying a hibf with --index without the flag --hibf also segfaults.

### How to repeat the problem

Give raptor an empty .fastq query file. Give raptor a serialized HIBF without suppliying the --hibf flag

### Expected behaviour

For the empty input file I would expect: an error, a warning and/or simply an output file with no read classifications. 
For the missing --hibf I would expect: an error

### Actual behaviour

Segfaults

**Comment by eseiler** [comment]
I'll add a check for empty sequence files, this shouldn't segfault :)

The `--hibf` thing will be resolved once I update the raptor index to include the new parameters. The index will then be aware of whether it stores an HIBF or IBF.
