### ISSUE TITLE
[BUG] --compute minimiser function is broken

### ISSUE THREAD

**Issue by MitraDarja** [seqan/raptor#24]
When running ```raptor build --kmer 19 --window 23 --size 8m --compute-minimiser --output sequence_file```
I get a `seqan3::file_open_error'.
My assumption is that the parallel call does not work correctly and does not give worker the correct file name. I tried to print out the flle name and got nonsense as an output.

**Comment by eseiler** [comment]
> `raptor build --kmer 19 --window 23 --size 8m --compute-minimiser --output sequence_file`

There are no input files in the call. (We should throw when input list is empty).

**Comment by MitraDarja** [comment]
Ups, I forgot the filename. I gave it a fastq.gz file, which should work.

**Comment by eseiler** [comment]
#25 should fix it

We parsed the compressed file and treated it as having one path to a file per line
