### ISSUE TITLE
raptor installed with bioconda crashes

### ISSUE THREAD

**Issue by fplaza** [seqan/raptor#408]
Hi,

I have installed raptor with bioconda.
The program crashes with the following error message "Illegal instruction (core dumped)"
I am using CentOS 8. 

My CPU is quite old and does not have AVX2 extensions but it seems that they are activated by default:
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/raptor/build.sh

Many thanks for your help,
Florian

**Comment by eseiler** [comment]
Hey there,

is it possible for you to build raptor 3.0.1 from source? 

I will check how to provide multiple variants in a conda package (e.g., with/without AVX2).

**Comment by eseiler** [comment]
Would you mind posting the output of `lscpu`?

I would build for `SSE4`, `AVX2`, and `AVX512`. Just want to make sure that this works out for your CPU.

**Comment by fplaza** [comment]
Hi,

No I can't build raptor (at least easily) because the compiler and cmake versions are too old.
Here is the output of lscpu:
`Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm ssbd rsb_ctxsw ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts md_clear spec_ctrl intel_stibp flush_l1d`

**Comment by eseiler** [comment]
I updated the recipe and it was merged. A new version should be available for download.

Let me know if this one works :)

**Comment by fplaza** [comment]
Hi @eseiler,

Thanks for the update.
Unfortunately, the new executable does not work.
This time, raptor immediately stops without any message and returns an error code 1.

**Comment by eseiler** [comment]
Ah pity.

Can you run `grep -c -m 1 -E '\bsse2\b' /proc/cpuinfo`?
I'm wondering which command returns an error code. I guess `set -u` works, but with `set -e` something errors and the script exits. I don't have centos setup for testing it, it does work with other systems.

**Comment by fplaza** [comment]
After removing "set -eu", the raptor_sse4.2 executable is launched.
grep returns an error code when there is no match (with the commands testing for avx instructions on my machine)

**Comment by eseiler** [comment]
> After removing "set -eu", the raptor_sse4.2 executable is launched. 

That's good, so it at least works :)

> grep returns an error code when there is no match (with the commands testing for avx instructions on my machine)

Ok, so that seems to be different from other systems, where it apparently does not return an error due to `-c`.

Does 
```
grep -c -m 1 -E '\bavx2\b' /proc/cpuinfo || true
```
print `0`, and the return code `0` (via `echo $?`)?

If so, I would update the recipe to use `|| true`:

```bash
#!/bin/bash

set -eu

# -c : return count
# -m 1 : stop after first match, i.e. count is either 0 or 1
# -E : use extended regular expressions
# \b : matches any non alphanumeric character, i.e. space, tab, newline, etc.
HAS_SSE2=$(grep -c -m 1 -E '\bsse2\b' /proc/cpuinfo || true)
HAS_SSE4_2=$(grep -c -m 1 -E '\bsse4_2\b' /proc/cpuinfo || true)
HAS_AVX2=$(grep -c -m 1 -E '\bavx2\b' /proc/cpuinfo || true)
HAS_AVX512F=$(grep -c -m 1 -E '\bavx512f\b' /proc/cpuinfo || true)
HAS_AVX512BW=$(grep -c -m 1 -E '\bavx512bw\b' /proc/cpuinfo || true)
if [ ${HAS_AVX512F} -eq 1 ] && [ ${HAS_AVX512BW} -eq 1 ]; then
    HAS_AVX512=1
else
    HAS_AVX512=0
fi

if [ ${HAS_AVX512} -eq 1 ]; then
    raptor_avx512 "$@"
elif [ ${HAS_AVX2} -eq 1 ]; then
    raptor_avx2 "$@"
elif [ ${HAS_SSE4_2} -eq 1 ]; then
    raptor_sse4.2 "$@"
elif [ ${HAS_SSE2} -eq 1 ]; then
    raptor_sse2 "$@"
else
    raptor_none "$@"
fi
```

If not, I'll just remove the `-e`. In which case I would ask you to check if `set -u` works, just in case the variable is undefined because of the non-zero return.

Thanks for your help and patience!

**Comment by fplaza** [comment]
Yes, `grep -c -m 1 -E '\bavx2\b' /proc/cpuinfo || true`  works
